clear;
D1=dir('*h1*.mat');
RGB1=dir('*e1*.png');
D2=dir('*h2*.mat');
RGB2=dir('*e2*.png');
[n,~]=size(D1);
sample=load(D1(1).name);
[x,y]=size(sample.depth_array);
imgseq1=struct('rgb',cell(n,1),'depth',cell(n,1));
imgseq2=struct('rgb',cell(n,1),'depth',cell(n,1));
for i=1:n
    imgseq1(i).rgb=RGB1(i).name;
    imgseq1(i).depth=D1(i).name;
    imgseq2(i).rgb=RGB2(i).name;
    imgseq2(i).depth=D2(i).name;
end
BG1 = background (imgseq1,n,x,y);
BG2 = background (imgseq2,n,x,y);
figure;
subplot(2,2,1);
imagesc(BG1.depth);
colorbar;
title('depth cam1');
subplot(2,2,2);
imshow(uint8(BG1.rgb));
title('rgb cam1');
subplot(2,2,3);
imagesc(BG2.depth);
colorbar;
title('depth cam2');
subplot(2,2,4);
imshow(uint8(BG2.rgb));
title('rgb cam2');