close all;
clear;
load('cameraparametersAsus.mat');
subfolder='lab2';
img=1;
[x,y,imseq1,imseq2]=dir2struct('depth%d_%d.mat','rgb_image%d_%d.png',subfolder);
n=numel(imseq1);
[R21,T21]=getransactf(n,imseq1,imseq2,cam_params,x,y,subfolder,5);
%[R21,T21]=getfusedPC(imseq1(img),imseq2(img),cam_params,x,y,subfolder);
% load('R21lab2.mat');
% load('T21lab2.mat');
T21=T21(1,:)';
BG1 = backgrounD(imseq1,n,x*y,subfolder);
BG2 = backgrounD(imseq2,n,x*y,subfolder);
%plot2bg(BG1,BG2,x,y);
[feat_d,foreg,matches]=feat_detect(BG1,BG2,R21,T21,imseq1,imseq2,x,y,n,cam_params,subfolder);
objects=feat_match(feat_d,foreg);